sudo: required
services:
  - docker

before_install:
  - docker build -t denipermana/docker-react -f Dockerfile.dev .

script:
  - docker run denipermana/docker-react yarn test --coverage

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  app_name: docker-react-test
  on:
    branch: master